### ISSUE TITLE
Error !!! rive.load not a function

### ISSUE THREAD

**Issue by Zenfection1412** [dappsnation/ng-rive#44]
I'm using Angular 16
![CleanShot 2023-07-25 at 11 40 36](https://github.com/dappsnation/ng-rive/assets/44715845/9b83d3e5-64fe-4df2-8251-8ef90fef5aac)

**Comment by phpgeekfr** [comment]
I fixed this  by forcing this version of  canvas-advanced in package.json : `"@rive-app/canvas-advanced": "1.1.6",` 

With  `"ng-rive": "0.2.6"` and  angular 14

**Comment by Zenfection1412** [comment]
> I fixed this by forcing this version of canvas-advanced in package.json : `"@rive-app/canvas-advanced": "1.1.6",`
> 
> With `"ng-rive": "0.2.6"` and angular 14

not working bro !!!

**Comment by cozmik** [comment]
Is there any fix for this? Currently facing same challenge.. Angular 16

**Comment by GrandSchtroumpf** [comment]
Hello, it looks like rive has changed it's low level api since version 1.2. So I'll have to do some changes.
In the meantime you can use : 
- angular14 & ng-rive@0.2.6 &  @rive-app/canvas-advanced@1.1.6
- angular15/16 & ng-rive@0.2.7 & @rive-app/canvas-advanced@1.2.1

Sorry for the delay in answering
